from pykson import JsonObject, StringField


class Post(JsonObject):
    id = StringField()
    tags = StringField()
    created_at = StringField()
    author = StringField()
    change = StringField()
    source = StringField()
    score = StringField()
    md5 = StringField()
    file_size = StringField()
    file_ext = StringField()
    file_url = StringField()
    is_shown_in_index = StringField()
    jpeg_url = StringField()
    jpeg_width = StringField()
    jpeg_height = StringField()
    jpeg_file_size = StringField()
    rating = StringField()
    is_rating_locked = StringField()
    has_children = StringField()
    parent_id = StringField()
    status = StringField()
    is_pending = StringField()
    width = StringField()
    height = StringField()
    is_held = StringField()
    downloaded = StringField()
    downloaded_at = StringField()
    downloaded_by = StringField()
